### ISSUE TITLE
"Three_UART_One_Wire_No_SPI" mode failure with V1.6.16 and SAMD21E17

### ISSUE THREAD

**Issue by alejandroImagina** [mattairtech/ArduinoCore-samd#13]
Hi, I've tried to use this mode with a SAMD21E17 and it fails to compile. 

Searching in the library, I've found that in this mode, the Wire and the Third Serial share the SERCOM1 definition. I've already fixed it changing the definition of the Third Serial to use the SERCOM3 with it, and it works fine. 

But is something it should be fixed ;)

Regards

**Comment by mattairtech** [comment]
This was fixed in the latest beta release (https://github.com/mattairtech/ArduinoCore-samd/commit/849cd47b4ff5f2e57171c37b8d9ad4b995f49df0). Note that to avoid other conflicts, I used SERCOM3 for wire when appropriate (rather than changing the third serial).
