### ISSUE TITLE
D51 Xeno Mini Missing From Mattair Boards

### ISSUE THREAD

**Issue by davidbitton** [mattairtech/ArduinoCore-samd#15]
I just installed the bat build, and there is no entry for the D51 processor under the Xeno board. Has it not been released yet? Thanks!

**Comment by mattairtech** [comment]
D51 support was released in the latest beta (https://github.com/mattairtech/ArduinoCore-samd/commit/849cd47b4ff5f2e57171c37b8d9ad4b995f49df0).
