### ISSUE TITLE
Tools Menu Options

### ISSUE THREAD

**Issue by perigalacticon** [mattairtech/ArduinoCore-samd#8]
Hello I am trying this core for the first time.  I don't see most of the options that should be in the tools menu like:  "Bootloader Size Menu":

![mattairtecharduinocore-samd tools menu](https://user-images.githubusercontent.com/4515730/30491794-62a0ce08-9a0c-11e7-9c53-10bb06217eb0.png)

Is there something wrong with my installation?  I am using IDE 1.8.4.

**Comment by mattairtech** [comment]
Please use the Beta for now for all of the new menus (see https://github.com/mattairtech/ArduinoCore-samd/README.md). I will finally make the next beta version (which should be released in just over 1 week) the new release version as well. I intend to have more release versions from then on.

**Comment by mattairtech** [comment]
This is now in the release version. The beta track always includes the release versions as well.
